print("Enter 10 students names")
name=scan(what = character())
print("enter 10 std usn")
usn=scan(what = character())
print("enter marks obtained by 10 std")
marks=scan(what = double())
std_list=list(name,usn,marks)
cat("total marks of 10 students is ",unlist(std_list[[3]]))
avg=mean(std_list[[3]])
cat("class average is ",avg)