name = readline(prompt="enter your name:")
usn= readline(prompt="enter your usn:")
age = readline(prompt="enter your age:")
cgpa = readline(prompt="enter your cgpa:")
age=as.integer(age)
cgpa=as.numeric(cgpa)
cat("name=",name)
cat("\nusn=",usn)
cat("\nage=",age)
cat("\ncgpa=",cgpa)
